#!/bin/sh

set -eu
cd "$(dirname "$0")"

echo "Download base.img"; (
  mkdir -p download
  cd download

  [ -e base.img ] && echo "..already exists" && exit 0

  wget -O - \
    https://stable.release.core-os.net/amd64-usr/current/coreos_production_qemu_image.img.bz2 \
  | bzip2 -d > base.img
)

echo "Download ct"; (
  mkdir -p download
  cd download

  [ -e ct ] && echo "..already exists" && exit 0

  wget -O ct \
    https://github.com/coreos/container-linux-config-transpiler/releases/download/v0.9.0/ct-v0.9.0-x86_64-unknown-linux-gnu
  chmod 755 ct
)
