#!/bin/sh

set -eu
cd "$(dirname "$0")"

sudo ip link add br-core type bridge

# this dummy device is needed to set br-core mac address
# see: https://backreference.org/2010/07/28/linux-bridge-mac-addresses-and-dynamic-ports/
sudo ip link add if-core-0 type dummy

sudo ip link set if-core-0 address 52:54:00:00:00:00 master br-core down
sudo ip link set br-core address 52:54:00:00:00:00 up
sudo ip addr add 10.12.34.1/24 dev br-core

sudo iptables -t nat -I POSTROUTING -s 10.12.34.0/24 ! -d 10.12.34.0/24 -j MASQUERADE
