#!/usr/bin/env docker.sh

# Author: win@payfazz.com

name=devops-demo-ansible-$dirsum
image=$name
net=container:$("$dir/net" name)
must_local=y
opts="
  -v '$dir/..:/host_data'
"

pre_pull() {
  panic "Image '$image' can't be pulled, please build"
}

pre_start() {
  if [ "$1" = run ]; then
    exists image "$image" || command_build || panic "Failed to build image"
  fi
  case "$1" in
  run|start) "$dir/net" start || panic "Failed to start net container" ;;
  esac
}

post_start() {
  if [ "$1" = run ]; then
    main exec sh -ceu "
      addgroup -g '$(id -g)' user
      adduser -D -u '$(id -u)' -G user -s /bin/sh user
    " \
    || panic "Failed to setup container after it running"
  fi
}

command_build() {
  cd "$dir"
  tar c \
    ./dockerfiles/ansible.Dockerfile \
    ./extras/docker_pid1 \
  | docker build --pull -t "$image" -f dockerfiles/ansible.Dockerfile -
}

command_run_playbook() {
  main start || panic "Failed to start container"
  main exec_as user sh -ceu '
    cd /host_data/ansible-playbook
    exec ansible-playbook "$@"
  ' - "$@"
}
